import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>southxzx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <nav>
        <div className={styles.navList}>
          <ul>
            <li><a>Home</a></li>
            <li><a>Blog</a></li>
            <li><a>Showcase</a></li>
            <li><a>Contact</a></li>
          </ul>
        </div>
      </nav>

      <main className={styles.main}>
        <div className={`${styles.leftMain} ${styles.subMain}`}>
          <h2 className={styles.bigTitle}>
            Hi there!
          </h2>
          <p className={styles.smallTitle}>Such a idiot place but I'm glad that you're here.</p>
        </div>
        <div className={`${styles.rightMain} ${styles.subMain}`}>
          <div className={styles.rightMainBg}>
          </div>
          <div className={styles.rightMainImg}><Image src={"/images/nam_transparent.png"} width={450} height={540} objectFit='contain' />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
