enum ErrorResponse {
  CREATED_SUCCESFULLY = 'CREATED_SUCCESFULLY',
  UPDATED_SUCCESFULLY = 'UPDATED_SUCCESFULLY',
  REMOVED_SUCCESFULLY = 'REMOVED_SUCCESFULLY',
  INVALID_PARAMS = 'INVALID_PARAMS',
  NOT_FOUND = 'NOT_FOUND',
  FAILD_TO_CREATE = 'FAILD_TO_CREATE',
}

export {
  ErrorResponse
}